### PR TITLE
Ignore virtual devices

### LINKED ISSUE #73: [IMPROVEMENT] Improve network interface detection
We should ignore `virtual` interfaces inside machines, just stick to the real ones

### PR DESCRIPTION
**Pull request by 89luca89**
Fix #73

### CODE REVIEW

**Review by J4CKR3D — APPROVED** [review]

**Comment by alegrey91** [comment]
@89luca89 what about FreeBSD?
Is it unnecessary?

**Comment by 89luca89** [comment]
> @89luca89 what about FreeBSD?
> Is it unnecessary?

A bit different on how it's accomplished in Linux, I've included a simple fix to make life easier

**Comment by alegrey91** [comment]
Can you write something about this or in the doc? Just to take track of our decisions.

**Comment by 89luca89** [comment]
> Can you write something about this or in the doc? Just to take track of our decisions.

done

**Comment by alegrey91** [comment]
Good boy

**Review by alegrey91 — COMMENTED** [review]
Perfect

**Pull request merged**
